version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - hrms/target/hrms-0.0.1-SNAPSHOT.jar